---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2019/4/9 下午10:18
---

local lua2go = require('lua2go')
local antpath = lua2go.Load('./libcgoantpath.so')

lua2go.Externs[[
   extern GoString Version();
   extern GoInt32 IsPattern(GoString path);
   extern GoInt32 Match(GoString pattern,GoString path);
   extern GoInt32 MatchStart(GoString pattern,GoString path);
   extern GoString ExtractPathWithinPattern(GoString pattern,GoString path);
   extern GoMap ExtractUriTemplateVariables(GoString pattern,GoString path);
   extern GoString Combine(GoString pattern1,GoString pattern2);
   extern GoChan SetPathSeparator(GoString pathSeparator);
   extern GoChan SetCaseSensitive(GoInt32 caseSensitive);
   extern GoChan SetTrimTokens(GoInt32 trimTokens);
   extern GoChan SetCachePatterns(GoInt32 cachePatterns);
 ]]

local version = antpath.Version()

local v = lua2go.ToLuaString(version.p)
print(v)

local bn = antpath.Match(lua2go.ToGoString("/*/1.html"),lua2go.ToGoString("/100/1.html"))
if bn then
    print(true)
else
    print(false)
end

local combine = antpath.Combine(lua2go.ToGoString("/hotels/*"),lua2go.ToGoString("/booking"))
print(lua2go.ToLuaString(combine.p))



